version: '3'
#laruche-hive

services:
  web:
    build: .
    container_name: web
    working_dir: /app
    command: yarn
    volumes:
      - .:/app
    ports:
      - 80:3000
    networks:
      - default
  apis:
    container_name: apis
    network_mode: host
    image: golang
    volumes:
      - ${GOPATH}/src:/go/src
      - ${HOME}/laruche:/root/laruche
    command: sh start.sh


