version: '3'
#laruche-hive

services:
  web:
    build: .
    container_name: web
    working_dir: /app
    command: yarn start
    volumes:
      - .:/app
    ports:
      - 80:3000
    networks:
      - default

