version: '3'

services:

  web:
    build: .
    container_name: web
    working_dir: /app
    command: sh start.sh
    volumes:
      - .:/app
    expose:
      - "3000"

  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      # - ./nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/error.log:/etc/nginx/error_log.log
      # - ./nginx/cache/:/etc/nginx/cache
      - ./nginx:/etc/nginx
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
