export const main: string;
export const title: string;
export const projectBoard: string;
export const footer: string;
export const install: string;
export const installButton: string;
export const installDone: string;
export const copied: string;
export const copy: string;
